#!/usr/bin/perl

use File::Basename;


print "Uso Subeacopon dir_remoto ficheros\n";

my $workpath=shift;


my ( @FileNames  ) = @ARGV;



my $ficheros = '';
foreach my $file (@FileNames) {
        $ficheros .= " $file";
}

print "ncftpput -u u46335615 -p XXXXlarga copon.es $workpath $ficheros\n";
$res=`ncftpput -u u46335615 -p XXXXlarga copon.es $workpath $ficheros`;
